function Waveforms = importWaveTable()
% Used to import the generated wave table from the csv file.
% Auto-generated by MATLAB

% Initialize variables.
filename = 'C:\Users\nivelnola\Documents\Cooper Union Files\Y3-S2\ECE-413 Music & Engineering\Project 2\Waveforms.csv';
delimiter = ',';

% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

% Open the text file.
fileID = fopen(filename,'r');

% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string',  'ReturnOnError', false);

% Close the text file.
fclose(fileID);

% Create output variable
Waveforms = [dataArray{1:end-1}];

% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

end

